TaskScheduler: Task Class Reference
Task Class Reference abstract
Core task class for cooperative multitasking.
#include <TaskSchedulerDeclarations.h>
Public Member Functions
Task (unsigned long aInterval=0, long aIterations=0, Scheduler *aScheduler=NULL, bool aEnable=false, bool aSelfDestruct=false)
Task constructor with parameters.
Task (Scheduler *aScheduler)
Constructor for StatusRequest-based tasks (Object-Oriented callbacks)
virtual ~Task ()
Virtual destructor.
void setTimeout (unsigned long aTimeout, bool aReset=false)
Set overall task timeout.
void resetTimeout ()
Reset timeout counter.
unsigned long getTimeout ()
Get timeout value.
long untilTimeout ()
Get time until timeout.
bool timedOut ()
Check if task has timed out (deprecated)
bool isTimedOut ()
Check if task has timed out.
bool enable ()
Enable the task.
bool enableIfNot ()
Enable the task only if it was previously disabled.
bool enableDelayed (unsigned long aDelay=0)
Enable the task with delay.
bool restart ()
Restart the task.
bool restartDelayed (unsigned long aDelay=0)
Restart the task with delay.
void delay (unsigned long aDelay=0)
Delay the task execution.
void adjust (long aInterval)
Adjust task interval.
void forceNextIteration ()
Force next iteration to execute immediately.
bool disable ()
Disable the task.
void abort ()
Abort the task.
void cancel ()
Cancel the task.
bool isEnabled ()
Check if task is enabled.
bool isCanceled ()
Check if task is cancelled.
bool canceled ()
Check if task is cancelled (deprecated)
unsigned int getSchedulingOption ()
Get the current scheduling option for this task.
void setSchedulingOption (unsigned int aOption)
Set the scheduling option for this task.
void set (unsigned long aInterval, long aIterations)
Set task parameters (Object-Oriented callbacks)
void setInterval (unsigned long aInterval)
Set task execution interval.
void setIntervalNodelay (unsigned long aInterval, unsigned int aOption=0)
Set task interval without delay.
unsigned long getInterval ()
Get current task interval.
void setIterations (long aIterations)
Set number of iterations.
long getIterations ()
Get remaining iterations.
unsigned long getRunCounter ()
Get run counter.
void setSelfDestruct (bool aSelfDestruct=true)
Enable or disable self-destruction for this task.
bool getSelfDestruct ()
Check if self-destruction is enabled for this task.
virtual bool Callback ()=0
Pure virtual main task execution callback (Object-Oriented mode)
virtual bool OnEnable ()
Virtual task enable lifecycle callback (Object-Oriented mode)
virtual void OnDisable ()
Virtual task disable lifecycle callback (Object-Oriented mode)
bool isFirstIteration ()
Check if this is the first iteration.
bool isLastIteration ()
Check if this is the last iteration.
long getOverrun ()
Get the execution overrun time in microseconds.
long getStartDelay ()
Get the task start delay in microseconds.
bool waitFor (StatusRequest *aStatusRequest, unsigned long aInterval=0, long aIterations=1)
Wait for a StatusRequest to be signaled, then execute with new parameters.
bool waitForDelayed (StatusRequest *aStatusRequest, unsigned long aInterval=0, long aIterations=1)
Wait for a StatusRequest with delay, then execute with new parameters.
StatusRequest * getStatusRequest ()
Get the external StatusRequest object for this task.
StatusRequest * getInternalStatusRequest ()
Get the internal StatusRequest object for this task.
void setId (unsigned int aID)
Set the watchdog timer ID for this task.
unsigned int getId ()
Get the watchdog timer ID for this task.
void setControlPoint (unsigned int aPoint)
Set the control point identifier for this task.
unsigned int getControlPoint ()
Get the current control point identifier for this task.
void setLtsPointer (void *aPtr)
Set the Local Task Storage (LTS) pointer for this task.
void * getLtsPointer ()
Get the Local Task Storage (LTS) pointer for this task.
Task * getPreviousTask ()
Get pointer to the previous task in the scheduler's task chain.
Task * getNextTask ()
Get pointer to the next task in the scheduler's task chain.
void reset ()
Public Attributes
volatile _task_status iStatus
volatile unsigned long iInterval
volatile unsigned long iDelay
volatile unsigned long iPreviousMillis
unsigned int iOption
volatile long iOverrun
volatile long iStartDelay
volatile long iIterations
long iSetIterations
unsigned long iRunCounter
Task * iPrev
Task * iNext
Scheduler * iScheduler
StatusRequest * iStatusRequest
StatusRequest iMyStatusRequest
unsigned int iTaskID
unsigned int iControlPoint
void * iLTS
unsigned long iTimeout
unsigned long iStarttime
Friends
class Scheduler
Detailed Description
Core task class for cooperative multitasking.
A "Task" is an action, a part of the program logic, which requires scheduled execution. A concept of Task combines the following aspects:
Program code performing specific activities (callback methods)
Execution interval
Number of execution iterations
(Optionally) Execution start event (Status Request)
(Optionally) Pointer to a Local Task Storage area
Tasks perform certain functions, which could require periodic or one-time execution, update of specific variables, or waiting for specific events. Tasks also could be controlling specific hardware, or triggered by hardware interrupts.
For execution purposes Tasks are linked into execution chains, which are processed by the Scheduler in the order they were added (linked together).
Key Features:
Cooperative multitasking (non-preemptive)
Event-driven execution via StatusRequest objects
Dynamic parameter adjustment during runtime
Support for callback chaining and state machines
Built-in timeout and watchdog functionality
Local task storage for task-specific data
Note
Tasks are responsible for supporting cooperative multitasking by being "good neighbors", i.e., running their callback methods quickly in a non-blocking way, and releasing control back to the scheduler as soon as possible.
See also
Scheduler, StatusRequest
Definition at line 979 of file TaskSchedulerDeclarations.h.
Constructor & Destructor Documentation
Task() [1/2]
Task::Task (unsigned long aInterval = 0, long aIterations = 0, Scheduler * aScheduler = NULL, bool aEnable = false, bool aSelfDestruct = false) inline
Task constructor with parameters.
Parameters
aInterval Execution interval in milliseconds (or microseconds if _TASK_MICRO_RES enabled) (default = 0)
aIterations Number of iterations, -1 for indefinite execution (default = 0)
aScheduler Optional reference to existing scheduler. If supplied (not NULL) this task will be appended to the task chain (default = NULL)
aEnable Optional. Value of true will create task enabled (default = false)
Creates a task that is scheduled to run every aInterval milliseconds, aIterations times. All tasks are created disabled by default (unless aEnable = true). You have to explicitly enable the task for execution.
Note
Tasks do not remember the number of iterations set initially. After the iterations are done, internal iteration counter is 0. If you need to perform another set of iterations, you need to set the number of iterations again.
Tasks which performed all their iterations remain active.
Constructor, uses default values for the parameters so could be called with no parameters.
Definition at line 406 of file TaskScheduler.h.
References __task_id_counter, Scheduler::addTask(), enable(), iTaskID, reset(), set(), setSelfDestruct(), and Task().
Referenced by Task(), and Task().
Task() [2/2]
Task::Task (Scheduler * aScheduler) inline
Constructor for StatusRequest-based tasks (Object-Oriented callbacks)
Parameters
aScheduler Pointer to scheduler
Creates a Task for activation on event. Such tasks must run waitFor() method, their interval, iteration and enabled status will be set by that method.
Constructor with reduced parameter list for tasks created for StatusRequest only triggering (always immediate and only 1 iteration)
Definition at line 456 of file TaskScheduler.h.
References __task_id_counter, Scheduler::addTask(), iTaskID, reset(), set(), Task(), TASK_IMMEDIATE, and TASK_ONCE.
~Task()
Task::~Task () inline virtual
Virtual destructor.
Properly destroys the task object and cleans up resources.
Destructor. Makes sure the task disabled and deleted out of the chain prior to being deleted.
Definition at line 442 of file TaskScheduler.h.
References Scheduler::deleteTask(), disable(), iScheduler, and isEnabled().
Member Function Documentation
abort()
void Task::abort () inline
Abort the task.
Immediately stops task execution and marks it as aborted. Different from disable() in that it indicates abnormal termination. OnDisable method is NOT invoked for Aborted tasks.
Aborts task execution Task will no longer be executed by the scheduler AND ondisable method will not be called
Definition at line 920 of file TaskScheduler.h.
References _task_status::canceled, _task_status::enabled, getSelfDestruct(), iMyStatusRequest, _task_status::inonenable, iStatus, _task_status::sd_request, StatusRequest::signalComplete(), and TASK_SR_ABORT.
Referenced by Scheduler::processRequests().
adjust()
void Task::adjust (long aInterval) inline
Adjust task interval.
Parameters
aInterval New interval value (can be negative for adjustment)
Adjusts the task execution interval by the specified amount.
Adjusts Task execution with aInterval (if task is enabled).
Definition at line 813 of file TaskScheduler.h.
References iDelay, and iPreviousMillis.
Referenced by Scheduler::processRequests().
Callback()
virtual bool Task::Callback () inline pure virtual
Pure virtual main task execution callback (Object-Oriented mode)
This pure virtual method must be implemented by derived classes to define the task's main execution logic. Called by the scheduler when the task is ready to execute based on its timing and iteration settings.
Returns
bool True if the execution was "productive" (performed meaningful work), false if the task was idle. A productive return value prevents the scheduler from entering sleep mode on the next idle cycle, optimizing power management for active tasks.
Note
Only available when _TASK_OO_CALLBACKS compile-time option is enabled
This is a pure virtual function - derived classes MUST implement it
Return value affects power management in _TASK_SLEEP_ON_IDLE_RUN mode
See also
_TASK_OO_CALLBACKS, _TASK_SLEEP_ON_IDLE_RUN
Since
Version 3.0.0
Example:
class MyTask : public Task {
public:
    bool Callback() override {
        // Perform task work
        Serial.println("Task executing");
        return true; // Productive execution
    }
};
cancel()
void Task::cancel () inline
Cancel the task.
Marks the task as cancelled, indicating it was stopped before normal completion. OnDisable method is invoked if task was in enabled state.
Cancels task execution Task will no longer be executed by the scheduler. Ondisable method will be called after 'canceled' flag is set
Definition at line 937 of file TaskScheduler.h.
References _task_status::canceled, disable(), iMyStatusRequest, iStatus, StatusRequest::signalComplete(), and TASK_SR_ABORT.
Referenced by Scheduler::processRequests().
canceled()
bool Task::canceled () inline
Check if task is cancelled (deprecated)
Returns
true if task has been cancelled
Deprecated:
Use isCanceled() instead
Definition at line 1228 of file TaskSchedulerDeclarations.h.
References isCanceled().
delay()
void Task::delay (unsigned long aDelay = 0) inline
Delay the task execution.
Parameters
aDelay Delay in milliseconds (default = 0)
Schedules the task for execution after a delay, but does not change the enabled/disabled status of the task. A delay of 0 (zero) will delay task for current execution interval. Use forceNextIteration() method to force execution during immediate next scheduling pass.
Delays Task for execution after a delay = aInterval (if task is enabled). leaves task enabled or disabled if aDelay is zero, delays for the original scheduling interval from now
Definition at line 806 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, iDelay, iInterval, and iPreviousMillis.
Referenced by enableDelayed(), Scheduler::processRequests(), and setInterval().
disable()
bool Task::disable () inline
Disable the task.
Returns
Previous enabled state: true if task was enabled, false otherwise
Scheduler will not execute this task any longer, even if it remains in the chain. Task can be later re-enabled for execution. If not NULL, task's OnDisable method is invoked almost immediately (actually during the next scheduling pass). OnDisable is invoked only if task was in enabled state.
Disables task Task will no longer be executed by the scheduler Returns status of the task before disable was called (i.e., if the task was already disabled)
Definition at line 886 of file TaskScheduler.h.
References _task_status::enabled, getSelfDestruct(), Scheduler::iCurrent, iMyStatusRequest, _task_status::inonenable, iScheduler, iStatus, OnDisable(), _task_status::sd_request, and StatusRequest::signalComplete().
Referenced by cancel(), Scheduler::disableAll(), Scheduler::processRequests(), and ~Task().
enable()
bool Task::enable () inline
Enable the task.
Returns
true if task was successfully enabled
Enables the task and schedules it for immediate execution (without delay) at this or next scheduling pass. Scheduler will execute the next pass without any delay because there is a task which was enabled and requires execution.
Note
If task being enabled is not assigned to a scheduler and is not part of execution chain, then task will not be enabled.
enable() invokes task's OnEnable method (if not NULL) immediately, which can prepare task for execution. OnEnable must return true for task to be enabled. If OnEnable returns false, task remains disabled.
Warning
OnEnable is invoked every time enable() is called, regardless if task is already enabled. Alignment to current millis() is performed after OnEnable exits.
Enables the task schedules it for execution as soon as possible, and resets the RunCounter back to zero
Definition at line 705 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, _task_status::canceled, _task_status::enabled, Scheduler::iCurrent, iDelay, iInterval, iMyStatusRequest, _task_status::inonenable, iPreviousMillis, iRunCounter, iScheduler, iStatus, OnEnable(), resetTimeout(), StatusRequest::setWaiting(), and StatusRequest::signalComplete().
Referenced by Scheduler::enableAll(), enableDelayed(), enableIfNot(), Scheduler::processRequests(), restart(), Task(), waitFor(), and waitForDelayed().
enableDelayed()
bool Task::enableDelayed (unsigned long aDelay = 0) inline
Enable the task with delay.
Parameters
aDelay Delay before first execution in milliseconds (default = 0)
Returns
true if task was successfully enabled
Enables the task and schedules it for execution after a specific delay.
Enables the task and schedules it for execution after a delay = aInterval
Definition at line 766 of file TaskScheduler.h.
References delay(), enable(), _task_status::enabled, and iStatus.
Referenced by Scheduler::processRequests(), and restartDelayed().
enableIfNot()
bool Task::enableIfNot () inline
Enable the task only if it was previously disabled.
Returns
Previous enable state: true if task was already enabled, false if task was disabled
Since enable() schedules Task for execution immediately, this method provides a way to activate tasks and schedule them for immediate execution only if they are not active already. All NOTES from the enable() method apply.
Enables the task only if it was not enabled already Returns previous state (true if was already enabled, false if was not)
Definition at line 757 of file TaskScheduler.h.
References enable(), _task_status::enabled, and iStatus.
Referenced by Scheduler::processRequests().
forceNextIteration()
void Task::forceNextIteration () inline
Force next iteration to execute immediately.
Schedules the task for execution during immediate next scheduling pass. The Task must be already enabled prior to this method. Task's schedule is adjusted to run from this moment in time.
Note
If a task was running every 10 seconds: 10, 20, 30, calling forceNextIteration at 44th second will make subsequent schedule look like: 44, 54, 64, 74, ..
Schedules next iteration of Task for execution immediately (if enabled) leaves task enabled or disabled Task's original schedule is shifted, and all subsequent iterations will continue from this point in time
Definition at line 829 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, iDelay, iInterval, and iPreviousMillis.
Referenced by Scheduler::processRequests().
getControlPoint()
unsigned int Task::getControlPoint () inline
Get the current control point identifier for this task.
Returns the current control point identifier, indicating which execution phase or critical section the task is currently in or last executed. Useful for debugging hung tasks and execution flow analysis.
Returns
unsigned int Current control point identifier, or 0 if none set
Note
Only available when _TASK_WDT_IDS compile-time option is enabled
Returns the most recent control point set by setControlPoint()
Used for debugging and execution phase identification
Can help identify where tasks hang or fail
See also
setControlPoint(), getId(), _TASK_WDT_IDS
Since
Version 3.0.0
Example:
void monitorTaskCallback() {
    unsigned int controlPoint = criticalTask.getControlPoint();
    unsigned long lastRun = criticalTask.getRunCounter();
    if (lastRun == previousRunCount && controlPoint != 0) {
        Serial.print("Critical task hung at control point: ");
        Serial.println(controlPoint);
        // Take corrective action
    }
    previousRunCount = lastRun;
}
Definition at line 983 of file TaskScheduler.h.
References iControlPoint.
getId()
unsigned int Task::getId () inline
Get the watchdog timer ID for this task.
Returns the unique identifier assigned to this task for watchdog monitoring. Used by watchdog systems and monitoring code to identify which task is currently executing or has failed to respond.
Returns
unsigned int The task's watchdog ID, or 0 if no ID has been set
Note
Only available when _TASK_WDT_IDS compile-time option is enabled
Returns the ID set by setId(), or 0 for uninitialized tasks
Used for watchdog reset operations and task identification
See also
setId(), getControlPoint(), _TASK_WDT_IDS
Since
Version 3.0.0
Example:
void watchdogResetCallback() {
    unsigned int taskId = myTask.getId();
    if (taskId > 0) {
        // Reset watchdog for this specific task
        resetWatchdogTimer(taskId);
        Serial.print("Watchdog reset for task ID: ");
        Serial.println(taskId);
    }
}
Definition at line 981 of file TaskScheduler.h.
References iTaskID.
getInternalStatusRequest()
StatusRequest * Task::getInternalStatusRequest () inline
Get the internal StatusRequest object for this task.
Returns a pointer to the internal StatusRequest object used for advanced task coordination patterns within the same task or tightly coupled task groups. Provides finer control over task signaling and coordination mechanisms.
Returns
StatusRequest* Pointer to the task's internal StatusRequest object, or nullptr if StatusRequest functionality is not available
Note
Only available when _TASK_STATUS_REQUEST compile-time option is enabled
Internal StatusRequest provides advanced coordination capabilities
Used for complex task orchestration and state machine patterns
Separate from external StatusRequest for different coordination levels
See also
getStatusRequest(), waitFor(), StatusRequest
Since
Version 3.0.0
Example:
void complexCoordinationCallback() {
    StatusRequest* internalStatus = myTask.getInternalStatusRequest();
    // Use internal status for advanced coordination
    otherTask.waitForDelayed(internalStatus, 100, 1);
}
Definition at line 496 of file TaskScheduler.h.
References iMyStatusRequest.
getInterval()
unsigned long Task::getInterval () inline
Get current task interval.
Returns
Current execution interval in milliseconds (or microseconds)
Definition at line 560 of file TaskScheduler.h.
References iInterval.
getIterations()
long Task::getIterations () inline
Get remaining iterations.
Returns
Number of remaining iterations
Definition at line 562 of file TaskScheduler.h.
References iIterations.
getLtsPointer()
void * Task::getLtsPointer () inline
Get the Local Task Storage (LTS) pointer for this task.
Returns the pointer to task-specific data storage previously set with setLtsPointer(). Enables tasks to access their persistent data without relying on global variables or external storage mechanisms.
Returns
void* Pointer to task-local storage, or nullptr if none set
Note
Only available when _TASK_LTS_POINTER compile-time option is enabled
Returned pointer must be cast to appropriate data type
Returns nullptr if no LTS pointer has been set
Enables clean data encapsulation and object-oriented patterns
See also
setLtsPointer(), _TASK_LTS_POINTER
Since
Version 3.0.0
Example:
struct SensorData {
    float temperature;
    float humidity;
    unsigned long lastReading;
};
void sensorCallback() {
    SensorData* data = (SensorData*)sensorTask.getLtsPointer();
    if (data) {
        data->temperature = readTemperature();
        data->humidity = readHumidity();
        data->lastReading = millis();
        Serial.print("Temp: ");
        Serial.print(data->temperature);
        Serial.print("C, Humidity: ");
        Serial.print(data->humidity);
        Serial.println("%");
    }
}
Definition at line 990 of file TaskScheduler.h.
References iLTS.
getNextTask()
Task * Task::getNextTask () inline
Get pointer to the next task in the scheduler's task chain.
Returns a pointer to the task that follows this task in the scheduler's internal linked list. This enables forward chain traversal, task enumeration, and advanced scheduler analysis for custom task management operations.
Returns
Task* Pointer to the next task in the chain, or nullptr if:
This is the last task in the chain
Task is not currently registered with a scheduler
Task chain is empty
Note
Only available when _TASK_EXPOSE_CHAIN compile-time option is enabled
Exposes internal scheduler data structure for advanced operations
Chain order is registration order, not execution priority
Useful for iteration, monitoring, and custom scheduler algorithms
Warning
Direct chain manipulation can corrupt scheduler state
See also
getPreviousTask(), _TASK_EXPOSE_CHAIN
Since
Version 3.0.0
Example:
void printAllTasks(Task& firstTask) {
    Task* current = &firstTask;
    int taskCount = 0;
    Serial.println("=== Task Chain Report ===");
    while (current != nullptr) {
        taskCount++;
        Serial.print("Task ");
        Serial.print(taskCount);
        Serial.print(": Enabled=");
        Serial.print(current->isEnabled() ? "YES" : "NO");
        Serial.print(", Interval=");
        Serial.print(current->getInterval());
        Serial.print("ms, Iterations=");
        Serial.println(current->getIterations());
        current = current->getNextTask();
    }
    Serial.print("Total tasks: ");
    Serial.println(taskCount);
}
int countEnabledTasks(Task& anyTask) {
    // Find start of chain
    Task* start = &anyTask;
    while (start->getPreviousTask() != nullptr) {
        start = start->getPreviousTask();
    }
    // Count enabled tasks
    int enabledCount = 0;
    Task* current = start;
    while (current != nullptr) {
        if (current->isEnabled()) {
            enabledCount++;
        }
        current = current->getNextTask();
    }
    return enabledCount;
}
Definition at line 2192 of file TaskSchedulerDeclarations.h.
References iNext.
getOverrun()
long Task::getOverrun () inline
Get the execution overrun time in microseconds.
Returns the amount of time (in microseconds) that the task's execution exceeded its scheduled interval. This measures how much longer the task took to complete compared to its allocated time budget, helping identify timing violations and performance bottlenecks.
Returns
long Overrun time in microseconds. Positive values indicate the task ran longer than its interval, negative values indicate it finished early. Zero indicates the task completed exactly on schedule.
Note
Only available when _TASK_TIMECRITICAL compile-time option is enabled
Measured from scheduled execution time to actual completion time
Useful for real-time system analysis and performance optimization
See also
getStartDelay(), _TASK_TIMECRITICAL
Since
Version 3.0.0
Example:
void criticalTaskCallback() {
    // Perform time-critical work
    performCriticalOperation();
    // Check if we exceeded our time budget
    long overrun = myTask.getOverrun();
    if (overrun > 1000) { // More than 1ms overrun
        Serial.print("Warning: Task overrun by ");
        Serial.print(overrun);
        Serial.println(" microseconds");
    }
}
Definition at line 972 of file TaskScheduler.h.
References iOverrun.
getPreviousTask()
Task * Task::getPreviousTask () inline
Get pointer to the previous task in the scheduler's task chain.
Returns a pointer to the task that precedes this task in the scheduler's internal linked list. This enables task chain traversal, debugging, and advanced task management operations for custom scheduler behaviors.
Returns
Task* Pointer to the previous task in the chain, or nullptr if:
This is the first task in the chain
Task is not currently registered with a scheduler
Task chain is empty
Note
Only available when _TASK_EXPOSE_CHAIN compile-time option is enabled
Exposes internal scheduler data structure for advanced operations
Chain order may not correlate with execution order (depends on timing)
Useful for debugging, custom algorithms, and chain analysis
Warning
Direct chain manipulation can corrupt scheduler state
See also
getNextTask(), _TASK_EXPOSE_CHAIN
Since
Version 3.0.0
Example:
void analyzeTaskChain(Task& startTask) {
    Task* current = &startTask;
    int position = 0;
    // Walk backwards through the chain
    while (current->getPreviousTask() != nullptr) {
        current = current->getPreviousTask();
        position++;
    }
    Serial.print("Task is at position ");
    Serial.print(position);
    Serial.println(" from chain start");
}
void debugTaskChain(Scheduler& scheduler) {
    // Find chain relationships for debugging
    Serial.println("Task Chain Analysis:");
    // Implementation would traverse and analyze the chain
}
Definition at line 2126 of file TaskSchedulerDeclarations.h.
References iPrev.
getRunCounter()
unsigned long Task::getRunCounter () inline
Get run counter.
Returns
Number of times callback method has been invoked since last enable
The runCounter value is incremented before callback method is invoked. If a task is checking the runCounter value within its callback method, then the first run value is 1.
Definition at line 564 of file TaskScheduler.h.
References iRunCounter.
getSchedulingOption()
unsigned int Task::getSchedulingOption () inline
Get the current scheduling option for this task.
Returns the current scheduling behavior option that determines how the task's interval and iterations are managed during execution.
Available scheduling options:
TASK_SCHEDULE: Default behavior - interval countdown starts after OnEnable
TASK_SCHEDULE_NC: No countdown - interval countdown starts immediately upon enable
TASK_INTERVAL: Interval mode - maintains exact intervals regardless of execution time
Returns
unsigned int Current scheduling option value (TASK_SCHEDULE, TASK_SCHEDULE_NC, or TASK_INTERVAL)
Note
This method is only available when _TASK_SCHEDULING_OPTIONS compile-time option is enabled
See also
setSchedulingOption(), TASK_SCHEDULE, TASK_SCHEDULE_NC, TASK_INTERVAL
Since
Version 3.0.0
Definition at line 1248 of file TaskSchedulerDeclarations.h.
References iOption.
getSelfDestruct()
bool Task::getSelfDestruct () inline
Check if self-destruction is enabled for this task.
Returns whether the task is configured to automatically remove itself from the scheduler after completing its final iteration.
Returns
bool True if self-destruction is enabled, false otherwise
Note
This method is only available when _TASK_SELF_DESTRUCT compile-time option is enabled
See also
setSelfDestruct(), setIterations()
Since
Version 3.0.0
Definition at line 1383 of file TaskSchedulerDeclarations.h.
References iStatus, and _task_status::selfdestruct.
Referenced by abort(), and disable().
getStartDelay()
long Task::getStartDelay () inline
Get the task start delay in microseconds.
Returns the amount of time (in microseconds) between when the task was scheduled to start and when it actually began execution. This measures scheduler latency and helps identify system timing accuracy and load issues.
Returns
long Start delay in microseconds. Positive values indicate the task started later than scheduled, negative values indicate it started early. Zero indicates perfect timing accuracy.
Note
Only available when _TASK_TIMECRITICAL compile-time option is enabled
Measured from scheduled start time to actual execution start time
High values may indicate system overload or scheduler inefficiency
See also
getOverrun(), _TASK_TIMECRITICAL
Since
Version 3.0.0
Example:
void timingAnalysisCallback() {
    long startDelay = myTask.getStartDelay();
    long overrun = myTask.getOverrun();
    Serial.print("Start delay: ");
    Serial.print(startDelay);
    Serial.print("us, Overrun: ");
    Serial.print(overrun);
    Serial.println("us");
    if (startDelay > 500) {
        Serial.println("Warning: High scheduler latency detected");
    }
}
Definition at line 973 of file TaskScheduler.h.
References iStartDelay.
getStatusRequest()
StatusRequest * Task::getStatusRequest () inline
Get the external StatusRequest object for this task.
Returns a pointer to the StatusRequest object that other tasks can use to wait for this task's completion. This enables the creation of task dependency chains and sophisticated coordination patterns.
Returns
StatusRequest* Pointer to the task's external StatusRequest object, or nullptr if StatusRequest functionality is not available
Note
Only available when _TASK_STATUS_REQUEST compile-time option is enabled
External StatusRequest is signaled when task completes its iterations
Used by other tasks in waitFor() and waitForDelayed() calls
Different from getInternalStatusRequest() which is used for internal coordination
See also
getInternalStatusRequest(), waitFor(), StatusRequest
Since
Version 3.0.0
Example:
Task producerTask(1000, 5, producerCallback, &scheduler);
Task consumerTask(100, 1, consumerCallback, &scheduler);
void setupTasks() {
    // Consumer waits for producer to complete
    StatusRequest* producerStatus = producerTask.getStatusRequest();
    consumerTask.waitFor(producerStatus, 500, TASK_FOREVER);
}
Definition at line 495 of file TaskScheduler.h.
References iStatusRequest.
Referenced by Scheduler::timeUntilNextIteration().
getTimeout()
unsigned long Task::getTimeout () inline
Get timeout value.
Returns
Current timeout value in milliseconds (or microseconds)
Definition at line 783 of file TaskScheduler.h.
References iTimeout.
isCanceled()
bool Task::isCanceled () inline
Check if task is cancelled.
Returns
true if task has been cancelled
Definition at line 945 of file TaskScheduler.h.
References _task_status::canceled, and iStatus.
Referenced by canceled().
isEnabled()
bool Task::isEnabled () inline
Check if task is enabled.
Returns
true if task is enabled
Definition at line 558 of file TaskScheduler.h.
References _task_status::enabled, and iStatus.
Referenced by Scheduler::timeUntilNextIteration(), and ~Task().
isFirstIteration()
bool Task::isFirstIteration () inline
Check if this is the first iteration.
Returns
true if current pass is (or will be) a first iteration of the task
Definition at line 966 of file TaskScheduler.h.
References iRunCounter.
isLastIteration()
bool Task::isLastIteration () inline
Check if this is the last iteration.
Returns
true if current pass is the last iteration (for tasks with limited iterations only)
Definition at line 968 of file TaskScheduler.h.
References iIterations.
isTimedOut()
bool Task::isTimedOut () inline
Check if task has timed out.
Returns
true if task has timed out
Definition at line 794 of file TaskScheduler.h.
References iStatus, and _task_status::timeout.
Referenced by timedOut().
OnDisable()
void Task::OnDisable () inline virtual
Virtual task disable lifecycle callback (Object-Oriented mode)
Called when the task transitions from enabled to disabled state. Allows derived classes to implement custom cleanup logic, resource deallocation, or state preservation when the task is deactivated.
Note
Only available when _TASK_OO_CALLBACKS compile-time option is enabled
Called synchronously during disable() operation
Called during automatic disable (iteration completion, errors)
Default implementation performs no action
See also
_TASK_OO_CALLBACKS, disable(), OnEnable()
Since
Version 3.0.0
Example:
class ResourceTask : public Task {
public:
    void OnDisable() override {
        cleanupResources();
        saveState();
        Serial.println("Task disabled");
    }
};
Definition at line 570 of file TaskScheduler.h.
Referenced by disable().
OnEnable()
bool Task::OnEnable () inline virtual
Virtual task enable lifecycle callback (Object-Oriented mode)
Called when the task transitions from disabled to enabled state. Allows derived classes to implement custom initialization logic, resource allocation, or conditional enabling based on system state.
Returns
bool True to allow the task to be enabled, false to prevent enabling. Returning false keeps the task disabled despite the enable request.
Note
Only available when _TASK_OO_CALLBACKS compile-time option is enabled
Default implementation returns true (allow enabling)
Called synchronously during enable() operation
Conditional enabling useful for resource-dependent tasks
See also
_TASK_OO_CALLBACKS, enable(), OnDisable()
Since
Version 3.0.0
Example:
class ConditionalTask : public Task {
public:
    bool OnEnable() override {
        if (systemReady()) {
            initializeResources();
            return true; // Allow enabling
        }
        return false; // Prevent enabling
    }
};
Definition at line 569 of file TaskScheduler.h.
Referenced by enable().
reset()
void Task::reset () inline
Resets (initializes) the task/ Task is not enabled and is taken out out of the execution chain as a result
Definition at line 585 of file TaskScheduler.h.
References _task_status::canceled, _task_status::enabled, iControlPoint, iDelay, iInterval, iLTS, iMyStatusRequest, iNext, _task_status::inonenable, iOption, iOverrun, iPrev, iPreviousMillis, iRunCounter, iScheduler, iStartDelay, iStarttime, iStatus, iStatusRequest, iTimeout, _task_status::sd_request, StatusRequest::signalComplete(), TASK_SCHEDULE, _task_status::timeout, and _task_status::waiting.
Referenced by Task(), and Task().
resetTimeout()
void Task::resetTimeout () inline
Reset timeout counter.
Resets the timeout counter to start counting from the beginning.
Definition at line 778 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, iStarttime, iStatus, and _task_status::timeout.
Referenced by enable(), Scheduler::processRequests(), and setTimeout().
restart()
bool Task::restart () inline
Restart the task.
Returns
true if task was successfully restarted
For tasks with limited number of iterations only, restart method will re-enable the task, set the number of iterations back to last set value, and schedule task for execution as soon as possible.
Restarts task Task will run number of iterations again
Definition at line 953 of file TaskScheduler.h.
References enable(), iIterations, and iSetIterations.
Referenced by Scheduler::processRequests().
restartDelayed()
bool Task::restartDelayed (unsigned long aDelay = 0) inline
Restart the task with delay.
Parameters
aDelay Delay before first execution in milliseconds (default = 0)
Returns
true if task was successfully restarted
Same as restart() method, with the only difference being that Task is scheduled to run first iteration after a delay.
Restarts task delayed Task will run number of iterations again
Definition at line 961 of file TaskScheduler.h.
References enableDelayed(), iIterations, and iSetIterations.
Referenced by Scheduler::processRequests().
set()
void Task::set (unsigned long aInterval, long aIterations) inline
Set task parameters (Object-Oriented callbacks)
Parameters
aInterval Execution interval in milliseconds (or microseconds)
aIterations Number of iterations (-1 for infinite)
Allows dynamic control of task execution parameters in one method call.
Explicitly set Task execution parameters
Parameters
aInterval - execution interval in ms
aIterations - number of iterations, use -1 for no limit
aCallback - pointer to the callback method which executes the task actions
aOnEnable - pointer to the callback method which is called on enable()
aOnDisable - pointer to the callback method which is called on disable()
Definition at line 642 of file TaskScheduler.h.
References iIterations, iSetIterations, set(), and setInterval().
Referenced by Scheduler::processRequests(), set(), Task(), and Task().
setControlPoint()
void Task::setControlPoint (unsigned int aPoint) inline
Set the control point identifier for this task.
Assigns a control point identifier used for fine-grained execution monitoring and debugging. Control points can mark specific execution phases or critical sections within task callbacks for detailed system analysis.
Parameters
aPoint Control point identifier (application-defined meaning)
Note
Only available when _TASK_WDT_IDS compile-time option is enabled
Control points provide execution phase tracking within tasks
Used for debugging, profiling, and fine-grained monitoring
Meaning and usage are application-specific
See also
getControlPoint(), setId(), _TASK_WDT_IDS
Since
Version 3.0.0
Example:
void complexTaskCallback() {
    myTask.setControlPoint(1);  // Phase 1: Sensor reading
    readSensors();
    myTask.setControlPoint(2);  // Phase 2: Data processing
    processData();
    myTask.setControlPoint(3);  // Phase 3: Output generation
    generateOutput();
    myTask.setControlPoint(0);  // Phase complete
}
Definition at line 982 of file TaskScheduler.h.
References iControlPoint.
Referenced by Scheduler::processRequests().
setId()
void Task::setId (unsigned int aID) inline
Set the watchdog timer ID for this task.
Assigns a unique identifier to the task for watchdog timer monitoring. The ID is used by external watchdog systems to track task execution and detect hung or malfunctioning tasks in mission-critical applications.
Parameters
aID Unique identifier for watchdog monitoring (typically 0-255 range)
Note
Only available when _TASK_WDT_IDS compile-time option is enabled
ID should be unique across all tasks in the system
Used in conjunction with external watchdog hardware/software
Essential for safety-critical and mission-critical applications
See also
getId(), setControlPoint(), _TASK_WDT_IDS
Since
Version 3.0.0
Example:
Task criticalTask(1000, TASK_FOREVER, criticalCallback, &scheduler);
Task monitorTask(5000, TASK_FOREVER, monitorCallback, &scheduler);
void setup() {
    criticalTask.setId(1);  // Critical system task
    monitorTask.setId(2);   // System monitor task
}
void criticalCallback() {
    // Reset watchdog for this task ID
    resetWatchdog(criticalTask.getId());
}
Definition at line 980 of file TaskScheduler.h.
References iTaskID.
Referenced by Scheduler::processRequests().
setInterval()
void Task::setInterval (unsigned long aInterval) inline
Set task execution interval.
Parameters
aInterval New interval in milliseconds (or microseconds)
Next execution time calculation takes place after the callback method is called, so new interval will be used immediately by the scheduler. Execution is delayed by the provided interval. If immediate invocation is required, call forceNextIteration() after setting new interval or use setIntervalNoDelay() method.
Sets the execution interval. Task execution is delayed for aInterval Use enable() to schedule execution ASAP
Parameters
aInterval - new execution interval
Definition at line 839 of file TaskScheduler.h.
References delay(), and iInterval.
Referenced by Scheduler::processRequests(), set(), waitFor(), and waitForDelayed().
setIntervalNodelay()
void Task::setIntervalNodelay (unsigned long aInterval, unsigned int aOption = 0) inline
Set task interval without delay.
Parameters
aInterval New interval in milliseconds (or microseconds)
aOption How to handle the interval change (default = TASK_INTERVAL_KEEP) TASK_INTERVAL_KEEP - keep the current delay, new interval will be used after current delay expires TASK_INTERVAL_RECALC - recalculate next execution time based on new interval TASK_INTERVAL_RESET - reset schedule, next execution time and new interval are updated
Sets new interval and provides options for how to handle the timing change.
Sets the execution interval without delaying the task Task state does not change If Task is disabled, it would remain so
Parameters
aInterval - new execution interval
Definition at line 849 of file TaskScheduler.h.
References iDelay, iInterval, TASK_INTERVAL_RECALC, and TASK_INTERVAL_RESET.
Referenced by Scheduler::processRequests().
setIterations()
void Task::setIterations (long aIterations) inline
Set number of iterations.
Parameters
aIterations Number of iterations (-1 for infinite)
Tasks that ran through all their allocated iterations are disabled. SetIterations() method DOES NOT enable the task. Either enable explicitly, or use restart methods.
Sets number of iterations for the task if task is enabled, schedule for immediate execution
Parameters
aIterations - number of iterations, use -1 for no limit
Definition at line 662 of file TaskScheduler.h.
References iIterations, and iSetIterations.
Referenced by Scheduler::processRequests(), waitFor(), and waitForDelayed().
setLtsPointer()
void Task::setLtsPointer (void * aPtr) inline
Set the Local Task Storage (LTS) pointer for this task.
Assigns a pointer to task-specific data storage that persists across task executions. This enables tasks to maintain state, store working data, or reference external resources without using global variables.
Parameters
aPtr Pointer to task-local storage area (any data type)
Note
Only available when _TASK_LTS_POINTER compile-time option is enabled
Pointer can reference any data structure or object
Memory management is application responsibility
Enables object-oriented patterns and data encapsulation
See also
getLtsPointer(), _TASK_LTS_POINTER
Since
Version 3.0.0
Example:
struct TaskData {
    int counter;
    float average;
    bool initialized;
};
TaskData myTaskData = {0, 0.0, false};
Task dataTask(1000, TASK_FOREVER, dataCallback, &scheduler);
void setup() {
    dataTask.setLtsPointer(&myTaskData);
}
void dataCallback() {
    TaskData* data = (TaskData*)dataTask.getLtsPointer();
    if (data) {
        data->counter++;
        // Use task-specific data
    }
}
Definition at line 989 of file TaskScheduler.h.
References iLTS.
Referenced by Scheduler::processRequests().
setSchedulingOption()
void Task::setSchedulingOption (unsigned int aOption) inline
Set the scheduling option for this task.
Sets the scheduling behavior option that determines how the task's interval and iterations are managed during execution. This affects when the interval countdown begins and how timing is calculated.
Scheduling options:
TASK_SCHEDULE: (Default) Interval countdown starts after OnEnable callback completes
TASK_SCHEDULE_NC: No countdown - interval countdown starts immediately when task is enabled
TASK_INTERVAL: Interval mode - maintains exact intervals by accounting for execution time
Parameters
aOption The scheduling option to set (TASK_SCHEDULE, TASK_SCHEDULE_NC, or TASK_INTERVAL)
Note
This method is only available when _TASK_SCHEDULING_OPTIONS compile-time option is enabled
The scheduling option can be changed at any time, even when the task is running
Warning
Using TASK_INTERVAL may cause timing drift if task execution time exceeds the interval
See also
getSchedulingOption(), TASK_SCHEDULE, TASK_SCHEDULE_NC, TASK_INTERVAL
Since
Version 3.0.0
Definition at line 1270 of file TaskSchedulerDeclarations.h.
References iOption.
Referenced by Scheduler::processRequests().
setSelfDestruct()
void Task::setSelfDestruct (bool aSelfDestruct = true) inline
Enable or disable self-destruction for this task.
When self-destruction is enabled, the task will automatically delete itself from the scheduler after it completes its final iteration. This is useful for one-time or temporary tasks that should clean themselves up automatically.
Self-destruction behavior:
Task removes itself from the scheduler when it finishes its last iteration
Applies to tasks with finite iterations (setIterations() > 0)
Does not apply to infinite tasks (TASK_FOREVER iterations)
Task object memory is not freed - only removed from scheduler
Parameters
aSelfDestruct True to enable self-destruction, false to disable (default: true)
Note
This method is only available when _TASK_SELF_DESTRUCT compile-time option is enabled
Self-destruction only occurs after the task naturally completes its iterations
Manually disabled tasks will not self-destruct
Warning
Ensure task object remains valid until self-destruction occurs
See also
getSelfDestruct(), setIterations(), disable()
Since
Version 3.0.0
Definition at line 1369 of file TaskSchedulerDeclarations.h.
References iStatus, and _task_status::selfdestruct.
Referenced by Task().
setTimeout()
void Task::setTimeout (unsigned long aTimeout, bool aReset = false) inline
Set overall task timeout.
Parameters
aTimeout Timeout period in milliseconds (or microseconds)
aReset Whether to reset timeout counter (default = false)
Any task can be set to time out after a certain period of time. Timeout can be reset, so it can be used as an individual Task's watchdog timer.
Definition at line 773 of file TaskScheduler.h.
References iTimeout, and resetTimeout().
Referenced by Scheduler::processRequests().
timedOut()
bool Task::timedOut () inline
Check if task has timed out (deprecated)
Returns
true if task has timed out
Deprecated:
Use isTimedOut() instead
Definition at line 1097 of file TaskSchedulerDeclarations.h.
References isTimedOut().
untilTimeout()
long Task::untilTimeout () inline
Get time until timeout.
Returns
Number of milliseconds (or microseconds) until timeout occurs
Returns negative value if timeout has already occurred.
Definition at line 787 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, iStarttime, and iTimeout.
waitFor()
bool Task::waitFor (StatusRequest * aStatusRequest, unsigned long aInterval = 0, long aIterations = 1) inline
Wait for a StatusRequest to be signaled, then execute with new parameters.
Suspends this task until the specified StatusRequest is signaled by another task, then reconfigures this task with new interval and iterations before resuming. Enables sophisticated inter-task communication and coordination patterns.
Parameters
aStatusRequest Pointer to StatusRequest object to wait for
aInterval New execution interval in milliseconds (default: 0 = keep current)
aIterations New iteration count (default: 1 = single execution)
Returns
bool True if wait was successful and task was reconfigured, false if StatusRequest is invalid or operation failed
Note
Only available when _TASK_STATUS_REQUEST compile-time option is enabled
Task becomes inactive until StatusRequest is signaled
StatusRequest must be signaled by another task's completion
Interval of 0 keeps current task interval unchanged
See also
waitForDelayed(), getStatusRequest(), StatusRequest
Since
Version 3.0.0
Example:
Task task1(1000, TASK_FOREVER, task1Callback, &scheduler);
Task task2(500, 1, task2Callback, &scheduler);
void task1Callback() {
    // Wait for task2 to complete, then run every 200ms for 5 iterations
    if (task1.waitFor(task2.getStatusRequest(), 200, 5)) {
        Serial.println("Task1 resumed after task2 completion");
    }
}
Sets a Task to wait until a particular event completes
Parameters
aStatusRequest - a pointer for the StatusRequest to wait for. If aStatusRequest is NULL, request for waiting is ignored, and the waiting task is not enabled.
Definition at line 522 of file TaskScheduler.h.
References _TASK_SR_NODELAY, enable(), iStatus, iStatusRequest, setInterval(), setIterations(), and _task_status::waiting.
Referenced by Scheduler::processRequests().
waitForDelayed()
bool Task::waitForDelayed (StatusRequest * aStatusRequest, unsigned long aInterval = 0, long aIterations = 1) inline
Wait for a StatusRequest with delay, then execute with new parameters.
Similar to waitFor() but introduces an additional delay before the task becomes eligible for execution after the StatusRequest is signaled. Useful for staggered execution and preventing simultaneous task activation.
Parameters
aStatusRequest Pointer to StatusRequest object to wait for
aInterval New execution interval in milliseconds (default: 0 = keep current)
aIterations New iteration count (default: 1 = single execution)
Returns
bool True if wait was successful and task was reconfigured, false if StatusRequest is invalid or operation failed
Note
Only available when _TASK_STATUS_REQUEST compile-time option is enabled
Adds scheduling delay after StatusRequest is signaled
Prevents immediate execution, allowing for staggered task activation
Interval of 0 keeps current task interval unchanged
See also
waitFor(), getStatusRequest(), StatusRequest
Since
Version 3.0.0
Example:
void coordinatorCallback() {
    // Wait for sensor task, then start processing with 1 second delay
    if (processingTask.waitForDelayed(sensorTask.getStatusRequest(), 1000, 10)) {
        Serial.println("Processing will start 1 second after sensor completion");
    }
}
Definition at line 533 of file TaskScheduler.h.
References _TASK_SR_DELAY, enable(), iStatus, iStatusRequest, setInterval(), setIterations(), and _task_status::waiting.
Referenced by Scheduler::processRequests().
Friends And Related Symbol Documentation
Scheduler
friend class Scheduler friend
Definition at line 980 of file TaskSchedulerDeclarations.h.
Member Data Documentation
iControlPoint
unsigned int Task::iControlPoint
Definition at line 2232 of file TaskSchedulerDeclarations.h.
Referenced by Scheduler::execute(), getControlPoint(), reset(), and setControlPoint().
iDelay
volatile unsigned long Task::iDelay
Definition at line 2200 of file TaskSchedulerDeclarations.h.
Referenced by adjust(), delay(), enable(), forceNextIteration(), reset(), setIntervalNodelay(), and Scheduler::timeUntilNextIteration().
iInterval
volatile unsigned long Task::iInterval
Definition at line 2199 of file TaskSchedulerDeclarations.h.
Referenced by delay(), enable(), forceNextIteration(), getInterval(), reset(), setInterval(), and setIntervalNodelay().
iIterations
volatile long Task::iIterations
Definition at line 2212 of file TaskSchedulerDeclarations.h.
Referenced by getIterations(), isLastIteration(), restart(), restartDelayed(), set(), and setIterations().
iLTS
void* Task::iLTS
Definition at line 2236 of file TaskSchedulerDeclarations.h.
Referenced by Scheduler::currentLts(), getLtsPointer(), reset(), and setLtsPointer().
iMyStatusRequest
StatusRequest Task::iMyStatusRequest
Definition at line 2227 of file TaskSchedulerDeclarations.h.
Referenced by abort(), cancel(), disable(), enable(), getInternalStatusRequest(), and reset().
iNext
Task * Task::iNext
Definition at line 2222 of file TaskSchedulerDeclarations.h.
Referenced by Scheduler::addTask(), Scheduler::deleteTask(), Scheduler::disableAll(), Scheduler::enableAll(), Scheduler::execute(), getNextTask(), and reset().
iOption
unsigned int Task::iOption
Definition at line 2204 of file TaskSchedulerDeclarations.h.
Referenced by getSchedulingOption(), reset(), and setSchedulingOption().
iOverrun
volatile long Task::iOverrun
Definition at line 2208 of file TaskSchedulerDeclarations.h.
Referenced by getOverrun(), and reset().
iPrev
Task* Task::iPrev
Definition at line 2222 of file TaskSchedulerDeclarations.h.
Referenced by Scheduler::addTask(), Scheduler::deleteTask(), getPreviousTask(), and reset().
iPreviousMillis
volatile unsigned long Task::iPreviousMillis
Definition at line 2201 of file TaskSchedulerDeclarations.h.
Referenced by adjust(), delay(), enable(), forceNextIteration(), reset(), and Scheduler::timeUntilNextIteration().
iRunCounter
unsigned long Task::iRunCounter
Definition at line 2214 of file TaskSchedulerDeclarations.h.
Referenced by enable(), getRunCounter(), isFirstIteration(), and reset().
iScheduler
Scheduler* Task::iScheduler
Definition at line 2223 of file TaskSchedulerDeclarations.h.
Referenced by Scheduler::addTask(), Scheduler::deleteTask(), disable(), enable(), reset(), and ~Task().
iSetIterations
long Task::iSetIterations
Definition at line 2213 of file TaskSchedulerDeclarations.h.
Referenced by restart(), restartDelayed(), set(), and setIterations().
iStartDelay
volatile long Task::iStartDelay
Definition at line 2209 of file TaskSchedulerDeclarations.h.
Referenced by getStartDelay(), and reset().
iStarttime
unsigned long Task::iStarttime
Definition at line 2241 of file TaskSchedulerDeclarations.h.
Referenced by reset(), StatusRequest::resetTimeout(), resetTimeout(), StatusRequest::setWaiting(), StatusRequest::StatusRequest(), StatusRequest::untilTimeout(), and untilTimeout().
iStatus
volatile _task_status Task::iStatus
Definition at line 2198 of file TaskSchedulerDeclarations.h.
Referenced by abort(), cancel(), disable(), Scheduler::disableAll(), enable(), enableDelayed(), enableIfNot(), getSelfDestruct(), StatusRequest::getStatus(), isCanceled(), isEnabled(), isTimedOut(), reset(), resetTimeout(), setSelfDestruct(), StatusRequest::setWaiting(), StatusRequest::signal(), StatusRequest::signalComplete(), StatusRequest::StatusRequest(), waitFor(), and waitForDelayed().
iStatusRequest
StatusRequest* Task::iStatusRequest
Definition at line 2226 of file TaskSchedulerDeclarations.h.
Referenced by getStatusRequest(), reset(), waitFor(), and waitForDelayed().
iTaskID
unsigned int Task::iTaskID
Definition at line 2231 of file TaskSchedulerDeclarations.h.
Referenced by getId(), setId(), Task(), and Task().
iTimeout
unsigned long Task::iTimeout
Definition at line 2240 of file TaskSchedulerDeclarations.h.
Referenced by getTimeout(), reset(), setTimeout(), StatusRequest::StatusRequest(), StatusRequest::untilTimeout(), and untilTimeout().
The documentation for this class was generated from the following files:
src/TaskSchedulerDeclarations.h
src/TaskScheduler.h