TaskScheduler: Scheduler Class Reference
Scheduler Class Reference
Task scheduler for cooperative multitasking.
#include <TaskSchedulerDeclarations.h>
Public Member Functions
Scheduler ()
Default constructor.
void init ()
Initialize the scheduler.
void addTask (Task &aTask)
Add task to execution chain.
void deleteTask (Task &aTask)
Delete task from execution chain.
void pause ()
Pause the scheduler.
void resume ()
Resume the scheduler.
void enable ()
Enable the scheduler.
void disable ()
Disable the scheduler.
void disableAll (bool aRecursive=true)
Disable all tasks (with priority support)
void enableAll (bool aRecursive=true)
Enable all tasks (with priority support)
void startNow (bool aRecursive=true)
Set all tasks to start immediately (with priority support)
bool execute ()
Execute one scheduling pass.
Task & currentTask ()
Get reference to currently executing task (deprecated)
Task * getCurrentTask ()
Get pointer to currently executing task.
long timeUntilNextIteration (Task &aTask)
Get time until next iteration of a task.
unsigned long getActiveTasks ()
Get number of active tasks.
unsigned long getTotalTasks ()
Get total number of tasks.
unsigned long getInvokedTasks ()
Get number of invoked tasks.
void allowSleep (bool aState=true)
Enable or disable sleep mode during idle scheduler cycles.
void setSleepMethod (SleepCallback aCallback)
Set custom sleep implementation callback.
void * currentLts ()
Get Local Task Storage pointer of currently executing task.
bool isOverrun ()
Check if any task execution overran its allocated time.
void cpuLoadReset ()
Reset CPU load measurement counters.
unsigned long getCpuLoadCycle ()
Get total CPU cycle time in microseconds.
unsigned long getCpuLoadIdle ()
Get total CPU idle time in microseconds.
unsigned long getCpuLoadTotal ()
Get total CPU load percentage.
void setHighPriorityScheduler (Scheduler *aScheduler)
Sets a higher priority scheduler for priority-based task scheduling.
Task * getFirstTask ()
Returns a pointer to the first task in the scheduler's task chain.
Task * getLastTask ()
Returns a pointer to the last task in the scheduler's task chain.
bool requestAction (_task_request_t *aRequest)
Queues a task operation request for thread-safe execution.
bool requestAction (void *aObject, _task_request_type_t aType, unsigned long aParam1, unsigned long aParam2, unsigned long aParam3, unsigned long aParam4, unsigned long aParam5)
Queues a task operation request with individual parameters for thread-safe execution.
void processRequests ()
Static Public Member Functions
static Scheduler & currentScheduler ()
Returns a reference to the currently executing scheduler.
Public Attributes
Task * iFirst
Task * iLast
Task * iCurrent
volatile bool iPaused
volatile bool iEnabled
unsigned long iActiveTasks
unsigned long iTotalTasks
unsigned long iInvokedTasks
bool iAllowSleep
Scheduler * iHighPriority
unsigned long iCPUStart
unsigned long iCPUCycle
unsigned long iCPUIdle
Friends
class Task
Detailed Description
Task scheduler for cooperative multitasking.
The Scheduler class manages the execution of tasks in a cooperative multitasking environment. It maintains a chain of tasks and executes them according to their schedules and priorities.
Key features:
Cooperative multitasking (non-preemptive)
Task chain management
Priority layer support
Sleep mode support for power saving
Thread safety options
Performance monitoring
The scheduler executes Tasks' callback methods in the order the tasks were added to the chain, from first to last. Scheduler stops and exits after processing the chain once in order to allow other statements in the main code of loop() method to run. This is referred to as a "scheduling pass".
Note
Normally, there is no need to have any other statements in the loop() method other than the Scheduler's execute() method.
See also
Task, StatusRequest
Definition at line 2269 of file TaskSchedulerDeclarations.h.
Constructor & Destructor Documentation
Scheduler()
Scheduler::Scheduler () inline
Default constructor.
Creates task scheduler with default parameters and an empty task queue.
Default constructor. Creates a scheduler with an empty execution chain.
Definition at line 999 of file TaskScheduler.h.
References SleepMethod().
Member Function Documentation
addTask()
void Scheduler::addTask (Task & aTask) inline
Add task to execution chain.
Parameters
aTask Reference to task to be added
Adds task to the execution queue (or chain) of tasks by appending it to the end of the chain. If two tasks are scheduled for execution, the sequence will match the order in which tasks were appended to the chain.
Note
Currently, changing the execution sequence in a chain dynamically is not supported. If you need to reorder the chain sequence – initialize the scheduler and re-add the tasks in a different order.
Appends task aTask to the tail of the execution chain.
Parameters
&aTask - reference to the Task to be appended.
Note
Task can only be part of the chain once.
Definition at line 1043 of file TaskScheduler.h.
References Task::iNext, Task::iPrev, and Task::iScheduler.
Referenced by Task::Task(), and Task::Task().
allowSleep()
void Scheduler::allowSleep (bool aState = true) inline
Enable or disable sleep mode during idle scheduler cycles.
Controls whether the scheduler should enter sleep mode when no tasks are ready for execution. Sleep mode reduces power consumption by halting CPU execution until the next task is scheduled to run.
Parameters
aState True to enable sleep mode (default), false to disable
Note
Only available when _TASK_SLEEP_ON_IDLE_RUN compile-time option is enabled
Sleep is only activated when all tasks return false from their callbacks
Tasks returning true (productive execution) prevent sleep on next cycle
Custom sleep method can be set with setSleepMethod()
See also
setSleepMethod(), _TASK_SLEEP_ON_IDLE_RUN
Since
Version 3.0.0
Example:
Scheduler powerEfficientScheduler;
void setup() {
    // Enable power-saving sleep mode
    powerEfficientScheduler.allowSleep(true);
    // Custom sleep implementation
    powerEfficientScheduler.setSleepMethod(customSleepCallback);
}
void customSleepCallback(unsigned long aTimeToSleep) {
    if (aTimeToSleep > 1000) {
        // Deep sleep for longer periods
        ESP.deepSleep(aTimeToSleep * 1000); // Convert to microseconds
    } else {
        // Light sleep for short periods
        delay(aTimeToSleep);
    }
}
Definition at line 1186 of file TaskScheduler.h.
Referenced by setHighPriorityScheduler().
cpuLoadReset()
void Scheduler::cpuLoadReset () inline
Reset CPU load measurement counters.
Resets the internal counters used for CPU load calculation, providing a fresh measurement baseline. This allows for periodic CPU load monitoring and performance analysis over specific time intervals.
Note
Only available when _TASK_TIMECRITICAL compile-time option is enabled
Resets both cycle time and idle time counters
Should be called before starting a new measurement period
Useful for periodic performance monitoring and load analysis
See also
getCpuLoadTotal(), getCpuLoadCycle(), getCpuLoadIdle()
Since
Version 3.0.0
Example:
void performanceMonitor() {
    static unsigned long lastReset = 0;
    unsigned long now = millis();
    // Measure CPU load every 10 seconds
    if (now - lastReset > 10000) {
        unsigned long cpuLoad = scheduler.getCpuLoadTotal();
        unsigned long cycleTime = scheduler.getCpuLoadCycle();
        unsigned long idleTime = scheduler.getCpuLoadIdle();
        Serial.print("10s Performance Report - CPU Load: ");
        Serial.print(cpuLoad);
        Serial.print("%, Cycle: ");
        Serial.print(cycleTime);
        Serial.print("us, Idle: ");
        Serial.print(idleTime);
        Serial.println("us");
        // Reset for next measurement period
        scheduler.cpuLoadReset();
        lastReset = now;
    }
}
Definition at line 1247 of file TaskScheduler.h.
References _task_micros().
currentLts()
void * Scheduler::currentLts () inline
Get Local Task Storage pointer of currently executing task.
Returns the LTS (Local Task Storage) pointer of the task that is currently being executed by the scheduler. This provides access to task-specific data from within the scheduler context or shared utilities.
Returns
void* Pointer to the current task's local storage, or nullptr if:
No task is currently executing
Current task has no LTS pointer set
Called outside of task execution context
Note
Only available when _TASK_LTS_POINTER compile-time option is enabled
Must be called from within task execution context for valid results
Returned pointer must be cast to appropriate data type
Useful for shared utilities that need access to current task data
See also
Task::setLtsPointer(), Task::getLtsPointer(), _TASK_LTS_POINTER
Since
Version 3.0.0
Example:
struct TaskData {
    int sensorValue;
    float average;
    bool alertFlag;
};
void sharedUtilityFunction() {
    TaskData* currentData = (TaskData*)scheduler.currentLts();
    if (currentData) {
        // Access current task's data
        Serial.print("Current task sensor value: ");
        Serial.println(currentData->sensorValue);
        if (currentData->sensorValue > THRESHOLD) {
            currentData->alertFlag = true;
        }
    }
}
void taskCallback() {
    // Task-specific work
    readSensors();
    // Call shared utility that accesses current task's LTS
    sharedUtilityFunction();
}
Definition at line 1241 of file TaskScheduler.h.
References Task::iLTS.
currentScheduler()
static Scheduler & Scheduler::currentScheduler () inline static
Returns a reference to the currently executing scheduler.
This static method provides access to the scheduler that is currently executing tasks. It's primarily used internally by the library to maintain context during task execution and to support priority-based scheduling operations.
Returns
Reference to the currently active scheduler instance
Note
This method is only available when _TASK_PRIORITY compilation option is enabled.
This is a static method that can be called without a scheduler instance.
The returned reference is valid only during task execution context.
Warning
Do not store the returned reference for long-term use as the current scheduler context changes during execution.
See also
setHighPriorityScheduler()
_TASK_PRIORITY
Example usage:
void taskCallback() {
    // Get reference to the scheduler executing this task
    Scheduler& currentSched = Scheduler::currentScheduler();
    // Access scheduler information
    Serial.print("Active tasks: ");
    Serial.println(currentSched.size());
}
Definition at line 2882 of file TaskSchedulerDeclarations.h.
References iCurrentScheduler.
currentTask()
Task & Scheduler::currentTask () inline
Get reference to currently executing task (deprecated)
Returns
Reference to the currently active task
Deprecated:
Use getCurrentTask() instead
Definition at line 1237 of file TaskScheduler.h.
deleteTask()
void Scheduler::deleteTask (Task & aTask) inline
Delete task from execution chain.
Parameters
aTask Reference to task to be deleted
Deletes task from the execution chain. The chain of remaining tasks is linked together. It is not required to delete a task from the chain. A disabled task will not be executed anyway, but you save a few microseconds per scheduling pass by deleting it.
Deletes specific Task from the execution chain
Parameters
&aTask - reference to the task to be deleted from the chain
Definition at line 1072 of file TaskScheduler.h.
References Task::iNext, Task::iPrev, and Task::iScheduler.
Referenced by Task::~Task().
disable()
void Scheduler::disable () inline
Disable the scheduler.
Disables the scheduler, preventing any task execution.
Definition at line 2333 of file TaskSchedulerDeclarations.h.
References iEnabled.
disableAll()
void Scheduler::disableAll (bool aRecursive = true) inline
Disable all tasks (with priority support)
Parameters
aRecursive If true (default), disable higher priority tasks as well
Convenient method to disable majority of tasks.
Disables all tasks in the execution chain Convenient for error situations, when the only task remaining active is an error processing task
Parameters
aRecursive - if true, tasks of the higher priority chains are disabled as well recursively
Definition at line 1118 of file TaskScheduler.h.
References Task::disable(), disableAll(), Task::iNext, Task::iStatus, and _task_status::sd_request.
Referenced by disableAll().
enable()
void Scheduler::enable () inline
Enable the scheduler.
Enables the scheduler for task execution.
Definition at line 2327 of file TaskSchedulerDeclarations.h.
References iEnabled.
enableAll()
void Scheduler::enableAll (bool aRecursive = true) inline
Enable all tasks (with priority support)
Parameters
aRecursive If true (default), enable higher priority tasks as well
Convenient method to enable majority of tasks.
Enables all the tasks in the execution chain
Parameters
aRecursive - if true, tasks of the higher priority chains are enabled as well recursively
Definition at line 1148 of file TaskScheduler.h.
References Task::enable(), enableAll(), and Task::iNext.
Referenced by enableAll().
execute()
bool Scheduler::execute () inline
Execute one scheduling pass.
Returns
true if none of the tasks' callback methods was invoked (true = idle run)
Executes one scheduling pass, including (in case of the base priority scheduler) end-of-pass sleep. This method should be placed inside the loop() method of the sketch. Since execute exits after every pass, you can put additional statements after execute inside the loop().
If layered task prioritization is enabled, all higher priority tasks will be evaluated and invoked by the base execute() method. There is no need to call execute() of the higher priority schedulers explicitly.
The execute method performs the following steps:
Call higher priority scheduler's execute method, if provided
Ignore task completely if it is disabled
Disable task if it ran out of iterations (calling OnDisable, if necessary)
Check if task is waiting on a StatusRequest object, and make appropriate scheduling arrangements
Perform necessary timing calculations
Invoke task's callback method, if it is time to do so, and one is provided
Put microcontroller to sleep (if requested and supported) if none of the tasks were invoked
Note
Schedule-related calculations are performed prior to task's callback method invocation. This allows tasks to manipulate their runtime parameters (like execution interval) directly.
Makes one pass through the execution chain. Tasks are executed in the order they were added to the chain There is no concept of priority Different pseudo "priority" could be achieved by running task more frequently
Definition at line 1526 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, _task_micros(), _TASK_SR_NODELAY, _task_yield(), Task::iControlPoint, iCurrentScheduler, Task::iNext, iSleepMethod, iSleepScheduler, StatusRequest::iStarttime, StatusRequest::iTimeout, StatusRequest::signalComplete(), TASK_INTERVAL, TASK_SCHEDULE_NC, TASK_SR_ABORT, and TASK_SR_TIMEOUT.
getActiveTasks()
unsigned long Scheduler::getActiveTasks () inline
Get number of active tasks.
Returns
Number of currently active (enabled) tasks
Definition at line 2437 of file TaskSchedulerDeclarations.h.
References iActiveTasks.
getCpuLoadCycle()
unsigned long Scheduler::getCpuLoadCycle () inline
Get total CPU cycle time in microseconds.
Returns the cumulative time spent in CPU cycles (active execution) since the last reset. This measures the total processing time used by all tasks and scheduler overhead.
Returns
unsigned long Total CPU cycle time in microseconds
Note
Only available when _TASK_TIMECRITICAL compile-time option is enabled
Includes task execution time and scheduler overhead
Used in conjunction with getCpuLoadIdle() for load calculation
Accumulates until reset with cpuLoadReset()
See also
getCpuLoadIdle(), getCpuLoadTotal(), cpuLoadReset()
Since
Version 3.0.0
Example:
void detailedPerformanceAnalysis() {
    unsigned long cycleTime = scheduler.getCpuLoadCycle();
    unsigned long idleTime = scheduler.getCpuLoadIdle();
    unsigned long totalTime = cycleTime + idleTime;
    if (totalTime > 0) {
        float cpuUtilization = (float)cycleTime / totalTime * 100.0;
        float idlePercentage = (float)idleTime / totalTime * 100.0;
        Serial.print("Detailed Analysis - Active: ");
        Serial.print(cpuUtilization, 2);
        Serial.print("%, Idle: ");
        Serial.print(idlePercentage, 2);
        Serial.print("%, Total time: ");
        Serial.print(totalTime);
        Serial.println("us");
    }
}
Definition at line 2729 of file TaskSchedulerDeclarations.h.
References iCPUCycle.
getCpuLoadIdle()
unsigned long Scheduler::getCpuLoadIdle () inline
Get total CPU idle time in microseconds.
Returns the cumulative time spent in idle state (no tasks executing) since the last reset. This measures the total time the CPU was available but not processing tasks.
Returns
unsigned long Total CPU idle time in microseconds
Note
Only available when _TASK_TIMECRITICAL compile-time option is enabled
Includes time spent waiting for next task execution
Used in conjunction with getCpuLoadCycle() for load calculation
Accumulates until reset with cpuLoadReset()
See also
getCpuLoadCycle(), getCpuLoadTotal(), cpuLoadReset()
Since
Version 3.0.0
Example:
void powerManagementAnalysis() {
    unsigned long idleTime = scheduler.getCpuLoadIdle();
    unsigned long cycleTime = scheduler.getCpuLoadCycle();
    // Calculate power saving potential
    if (idleTime > cycleTime) {
        float powerSavingPotential = (float)idleTime / (idleTime + cycleTime) * 100.0;
        Serial.print("Power saving potential: ");
        Serial.print(powerSavingPotential, 1);
        Serial.println("%");
        if (powerSavingPotential > 50.0) {
            Serial.println("Consider enabling sleep mode for better power efficiency");
        }
    }
}
Definition at line 2768 of file TaskSchedulerDeclarations.h.
References iCPUIdle.
getCpuLoadTotal()
unsigned long Scheduler::getCpuLoadTotal () inline
Get total CPU load percentage.
Calculates and returns the CPU load as a percentage based on the ratio of active cycle time to total time (cycle + idle). This provides a normalized measure of system utilization for performance monitoring.
Returns
unsigned long CPU load percentage (0-100)
Note
Only available when _TASK_TIMECRITICAL compile-time option is enabled
Returns percentage of time spent in active execution vs idle
Calculation: (cycleTime / (cycleTime + idleTime)) * 100
Returns 0 if no measurements have been taken
See also
getCpuLoadCycle(), getCpuLoadIdle(), cpuLoadReset()
Since
Version 3.0.0
Example:
void systemHealthMonitor() {
    unsigned long cpuLoad = scheduler.getCpuLoadTotal();
    // System health thresholds
    if (cpuLoad > 95) {
        Serial.println("CRITICAL: CPU load extremely high!");
        // Emergency measures
        disableNonEssentialTasks();
    } else if (cpuLoad > 80) {
        Serial.println("WARNING: High CPU load detected");
        // Performance optimization
        optimizeTaskIntervals();
    } else if (cpuLoad < 10) {
        Serial.println("INFO: Low CPU load - power optimization opportunity");
        // Enable power saving features
        scheduler.allowSleep(true);
    }
    // Log current status
    Serial.print("Current CPU Load: ");
    Serial.print(cpuLoad);
    Serial.println("%");
}
Definition at line 1254 of file TaskScheduler.h.
References _task_micros().
getCurrentTask()
Task * Scheduler::getCurrentTask () inline
Get pointer to currently executing task.
Returns
Pointer to the currently active task
Returns pointer to the task currently executing via execute() loop OR for OnEnable and OnDisable methods, pointer to the task being enabled or disabled. This distinction is important because one task can activate another. Could be used by callback methods to identify which Task invoked this callback method.
Definition at line 1238 of file TaskScheduler.h.
getFirstTask()
Task * Scheduler::getFirstTask () inline
Returns a pointer to the first task in the scheduler's task chain.
This method provides direct access to the first task in the internal linked list of tasks managed by this scheduler. It's primarily used for advanced task chain manipulation, debugging, and custom iteration over all tasks.
Returns
Pointer to the first task in the chain, or nullptr if no tasks are registered
Note
This method is only available when _TASK_EXPOSE_CHAIN compilation option is enabled.
The returned pointer should be treated as read-only to avoid corrupting the task chain.
Tasks are stored in a doubly-linked list internally.
Warning
Direct manipulation of the task chain can lead to undefined behavior. Use the standard addTask() and deleteTask() methods instead.
See also
getLastTask()
addTask()
deleteTask()
_TASK_EXPOSE_CHAIN
Example usage:
Scheduler ts;
Task t1, t2, t3;
ts.addTask(t1);
ts.addTask(t2);
ts.addTask(t3);
// Iterate through all tasks
Task* current = ts.getFirstTask();
while (current != nullptr) {
    Serial.print("Task ID: ");
    Serial.println(current->getId());
    current = current->getNext();
}
Definition at line 2925 of file TaskSchedulerDeclarations.h.
References iFirst.
getInvokedTasks()
unsigned long Scheduler::getInvokedTasks () inline
Get number of invoked tasks.
Returns
Number of tasks that were invoked during the last execute() pass
Definition at line 2449 of file TaskSchedulerDeclarations.h.
References iInvokedTasks.
getLastTask()
Task * Scheduler::getLastTask () inline
Returns a pointer to the last task in the scheduler's task chain.
This method provides direct access to the last task in the internal linked list of tasks managed by this scheduler. It's useful for reverse iteration through the task chain and for advanced task management operations.
Returns
Pointer to the last task in the chain, or nullptr if no tasks are registered
Note
This method is only available when _TASK_EXPOSE_CHAIN compilation option is enabled.
The returned pointer should be treated as read-only to avoid corrupting the task chain.
Tasks are stored in a doubly-linked list internally.
Warning
Direct manipulation of the task chain can lead to undefined behavior. Use the standard addTask() and deleteTask() methods instead.
See also
getFirstTask()
addTask()
deleteTask()
_TASK_EXPOSE_CHAIN
Example usage:
Scheduler ts;
Task t1, t2, t3;
ts.addTask(t1);
ts.addTask(t2);
ts.addTask(t3);
// Iterate through tasks in reverse order
Task* current = ts.getLastTask();
while (current != nullptr) {
    Serial.print("Task ID (reverse): ");
    Serial.println(current->getId());
    current = current->getPrev();
}
Definition at line 2966 of file TaskSchedulerDeclarations.h.
References iLast.
getTotalTasks()
unsigned long Scheduler::getTotalTasks () inline
Get total number of tasks.
Returns
Total number of tasks in the scheduler
Definition at line 2443 of file TaskSchedulerDeclarations.h.
References iTotalTasks.
init()
void Scheduler::init () inline
Initialize the scheduler.
Initializes the task queue and scheduler parameters. Executed as part of constructor, so doesn't need to be explicitly called after creation.
Note
By default scheduler is allowed to put processor to IDLE sleep mode. If this behavior was changed via allowSleep() method, init() will NOT reset the sleep parameter.
Initializes all internal varaibles
Definition at line 1015 of file TaskScheduler.h.
isOverrun()
bool Scheduler::isOverrun () inline
Check if any task execution overran its allocated time.
Returns whether any task in the current execution cycle exceeded its scheduled interval time. This provides system-wide timing violation detection for real-time system monitoring and performance analysis.
Returns
bool True if any task overran its allocated time, false otherwise
Note
Only available when _TASK_TIMECRITICAL compile-time option is enabled
Checks for timing violations across all tasks in the scheduler
Useful for system-wide real-time performance monitoring
Should be checked after each scheduler execution cycle
See also
Task::getOverrun(), getCpuLoadTotal(), _TASK_TIMECRITICAL
Since
Version 3.0.0
Example:
void loop() {
    scheduler.execute();
    // Check for system-wide timing violations
    if (scheduler.isOverrun()) {
        Serial.println("WARNING: System overrun detected!");
        // Log CPU load statistics
        unsigned long cpuLoad = scheduler.getCpuLoadTotal();
        Serial.print("CPU Load: ");
        Serial.print(cpuLoad);
        Serial.println("%");
        // Take corrective action
        if (cpuLoad > 90) {
            // Reduce system load
            disableNonCriticalTasks();
        }
    }
}
Definition at line 1245 of file TaskScheduler.h.
pause()
void Scheduler::pause () inline
Pause the scheduler.
Temporarily suspends all task execution. Tasks remain in their current state but will not be executed until resume() is called.
Definition at line 2315 of file TaskSchedulerDeclarations.h.
References iPaused.
processRequests()
void Scheduler::processRequests () inline
Definition at line 1289 of file TaskScheduler.h.
References Task::abort(), Task::adjust(), Task::cancel(), Task::delay(), Task::disable(), Task::enable(), Task::enableDelayed(), Task::enableIfNot(), Task::forceNextIteration(), _task_request_t::object_ptr, _task_request_t::param1, _task_request_t::param2, _task_request_t::param3, _task_request_t::param4, _task_request_t::param5, _task_request_t::req_type, StatusRequest::resetTimeout(), Task::resetTimeout(), Task::restart(), Task::restartDelayed(), Task::set(), Task::setControlPoint(), Task::setId(), Task::setInterval(), Task::setIntervalNodelay(), Task::setIterations(), Task::setLtsPointer(), Task::setSchedulingOption(), StatusRequest::setTimeout(), Task::setTimeout(), StatusRequest::setWaiting(), StatusRequest::signal(), StatusRequest::signalComplete(), TASK_REQUEST_ABORT_0, TASK_REQUEST_ADJUST_1, TASK_REQUEST_CANCEL_0, TASK_REQUEST_DELAY_1, TASK_REQUEST_DISABLE_0, TASK_REQUEST_ENABLE_0, TASK_REQUEST_ENABLEDELAYED_1, TASK_REQUEST_ENABLEIFNOT_0, TASK_REQUEST_FORCENEXTITERATION_0, TASK_REQUEST_RESETTIMEOUT_0, TASK_REQUEST_RESTART_0, TASK_REQUEST_RESTARTDELAYED_1, TASK_REQUEST_SET_5, TASK_REQUEST_SETCALLBACK_1, TASK_REQUEST_SETCONTROLPOINT_1, TASK_REQUEST_SETID_1, TASK_REQUEST_SETINTERVAL_1, TASK_REQUEST_SETINTERVALNODELAY_2, TASK_REQUEST_SETITERATIONS_1, TASK_REQUEST_SETLTSPOINTER_1, TASK_REQUEST_SETONDISABLE_1, TASK_REQUEST_SETONENABLE_1, TASK_REQUEST_SETSCHEDULINGOPTION_1, TASK_REQUEST_SETSELFDESTRUCT_1, TASK_REQUEST_SETTIMEOUT_2, TASK_REQUEST_WAITFOR, TASK_REQUEST_WAITFORDELAYED_3, TASK_SR_REQUEST_RESETTIMEOUT_0, TASK_SR_REQUEST_SETTIMEOUT_1, TASK_SR_REQUEST_SETWAITING_1, TASK_SR_REQUEST_SIGNAL_1, TASK_SR_REQUEST_SIGNALCOMPLETE_1, Task::waitFor(), and Task::waitForDelayed().
requestAction() [1/2]
bool Scheduler::requestAction (_task_request_t * aRequest) inline
Queues a task operation request for thread-safe execution.
This method places a pre-constructed request structure onto the task request queue for later processing during the next scheduler execution cycle. This provides thread-safe access to task operations from interrupt service routines or other execution contexts.
Parameters
aRequest Pointer to a _task_request_t structure containing the operation details. The structure should be properly initialized with the target object, operation type, and parameters.
Returns
true if the request was successfully queued, false if the queue is full
Note
This method is only available when _TASK_THREAD_SAFE compilation option is enabled.
The request structure must remain valid until the request is processed.
Requests are processed in FIFO order during scheduler execution.
The maximum number of queued requests is limited by the request queue size.
Warning
The aRequest pointer must point to a valid _task_request_t structure. Invalid pointers will cause undefined behavior.
See also
requestAction(void*, _task_request_type_t, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)
processRequests()
_task_request_t
_TASK_THREAD_SAFE
Example usage:
_task_request_t request;
request.object = &myTask;
request.type = TASK_REQUEST_ENABLE;
request.param1 = 0;
request.param2 = 0;
request.param3 = 0;
request.param4 = 0;
request.param5 = 0;
if (ts.requestAction(&request)) {
    Serial.println("Request queued successfully");
} else {
    Serial.println("Request queue full");
}
Definition at line 1270 of file TaskScheduler.h.
requestAction() [2/2]
bool Scheduler::requestAction (void * aObject, _task_request_type_t aType, unsigned long aParam1, unsigned long aParam2, unsigned long aParam3, unsigned long aParam4, unsigned long aParam5) inline
Queues a task operation request with individual parameters for thread-safe execution.
This method creates and queues a task operation request using individual parameters. It provides a convenient interface for thread-safe task operations without requiring manual construction of the request structure.
Parameters
aObject Pointer to the target object (Task or Scheduler) for the operation
aType Type of operation to perform (from _task_request_type_t enum)
aParam1 First parameter for the operation (interpretation depends on aType)
aParam2 Second parameter for the operation (interpretation depends on aType)
aParam3 Third parameter for the operation (interpretation depends on aType)
aParam4 Fourth parameter for the operation (interpretation depends on aType)
aParam5 Fifth parameter for the operation (interpretation depends on aType)
Returns
true if the request was successfully queued, false if the queue is full
Note
This method is only available when _TASK_THREAD_SAFE compilation option is enabled.
Parameter interpretation varies by operation type - see _task_request_type_t documentation.
Unused parameters should be set to 0.
Requests are processed in FIFO order during scheduler execution.
Warning
The aObject pointer must point to a valid Task or Scheduler instance. Invalid pointers will cause undefined behavior when the request is processed.
See also
requestAction(_task_request_t*)
processRequests()
_task_request_type_t
_TASK_THREAD_SAFE
Example usage:
// Request to enable a task from an ISR
void IRAM_ATTR sensorISR() {
    ts.requestAction(&sensorTask, TASK_REQUEST_ENABLE, 0, 0, 0, 0, 0);
}
// Request to restart a task with new interval
ts.requestAction(&myTask, TASK_REQUEST_RESTART, 5000, 0, 0, 0, 0); // 5 second interval
// Request to set task iterations
ts.requestAction(&myTask, TASK_REQUEST_SET_ITERATIONS, 10, 0, 0, 0, 0); // 10 iterations
Definition at line 1275 of file TaskScheduler.h.
References _task_request_t::req_type.
resume()
void Scheduler::resume () inline
Resume the scheduler.
Resumes task execution after pause().
Definition at line 2321 of file TaskSchedulerDeclarations.h.
References iPaused.
setHighPriorityScheduler()
void Scheduler::setHighPriorityScheduler (Scheduler * aScheduler) inline
Sets a higher priority scheduler for priority-based task scheduling.
This method establishes a hierarchical relationship between schedulers, allowing the current scheduler to defer execution to a higher priority scheduler when needed. This enables multi-level priority scheduling where critical tasks can preempt normal task execution.
Parameters
aScheduler Pointer to the higher priority scheduler to associate with this scheduler. Pass nullptr to remove the high priority scheduler association.
Note
This method is only available when _TASK_PRIORITY compilation option is enabled.
The high priority scheduler should be executed more frequently than this scheduler to ensure priority-based preemption works correctly.
Circular priority relationships should be avoided to prevent infinite loops.
See also
currentScheduler()
_TASK_PRIORITY
Example usage:
Scheduler highPriorityScheduler;
Scheduler normalScheduler;
// Set up priority relationship
normalScheduler.setHighPriorityScheduler(&highPriorityScheduler);
// In main loop, execute high priority first
highPriorityScheduler.execute();
normalScheduler.execute();
Sets scheduler for the higher priority tasks (support for layered task priority)
Parameters
aScheduler - pointer to a scheduler for the higher priority tasks
Definition at line 1172 of file TaskScheduler.h.
References allowSleep().
setSleepMethod()
void Scheduler::setSleepMethod (SleepCallback aCallback) inline
Set custom sleep implementation callback.
Assigns a custom callback function that will be called when the scheduler enters sleep mode. This allows for platform-specific power management implementations, such as deep sleep modes on ESP32 or low-power modes on Arduino boards.
Parameters
aCallback Function pointer to sleep callback with signature: void sleepCallback(unsigned long sleepTime) where sleepTime is in milliseconds
Note
Only available when _TASK_SLEEP_ON_IDLE_RUN compile-time option is enabled
Sleep callback receives the calculated sleep duration in milliseconds
Default implementation uses delay() if no custom callback is set
Callback should implement appropriate power management for the platform
See also
allowSleep(), SleepCallback, _TASK_SLEEP_ON_IDLE_RUN
Since
Version 3.0.0
Example:
void arduinoSleep(unsigned long sleepTime) {
    // Arduino-specific power management
    if (sleepTime > 100) {
        // Use watchdog timer for longer sleeps
        set_sleep_mode(SLEEP_MODE_PWR_DOWN);
        sleep_enable();
        sleep_mode();
        sleep_disable();
    } else {
        delay(sleepTime);
    }
}
void esp32Sleep(unsigned long sleepTime) {
    // ESP32-specific power management
    if (sleepTime > 1000) {
        esp_sleep_enable_timer_wakeup(sleepTime * 1000ULL);
        esp_light_sleep_start();
    } else {
        delayMicroseconds(sleepTime * 1000);
    }
}
scheduler.setSleepMethod(esp32Sleep);
Definition at line 1261 of file TaskScheduler.h.
References iSleepMethod, and iSleepScheduler.
startNow()
void Scheduler::startNow (bool aRecursive = true) inline
Set all tasks to start immediately (with priority support)
Parameters
aRecursive If true (default), affect higher priority tasks as well
Sets ALL active tasks to start execution immediately. Should be placed at the end of setup() method to prevent task execution race due to long running setup tasks. Any tasks which should execute after a delay should be explicitly delayed after call to startNow() method.
Definition at line 1193 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, and startNow().
Referenced by startNow().
timeUntilNextIteration()
long Scheduler::timeUntilNextIteration (Task & aTask) inline
Get time until next iteration of a task.
Parameters
aTask Reference to the task to query
Returns
Number of milliseconds (or microseconds) until next scheduled iteration
Returns 0 if next iteration is already due (or overdue). Returns -1 if a Task is not active or waiting on an event, and next iteration runtime cannot be determined.
Returns number millis or micros until next scheduled iteration of a given task
Parameters
aTask - reference to task which next iteration is in question
Definition at line 1218 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, Task::getStatusRequest(), Task::iDelay, Task::iPreviousMillis, Task::isEnabled(), and StatusRequest::pending().
Friends And Related Symbol Documentation
Task
friend class Task friend
Definition at line 2270 of file TaskSchedulerDeclarations.h.
Member Data Documentation
iActiveTasks
unsigned long Scheduler::iActiveTasks
Definition at line 3071 of file TaskSchedulerDeclarations.h.
Referenced by getActiveTasks().
iAllowSleep
bool Scheduler::iAllowSleep
Definition at line 3076 of file TaskSchedulerDeclarations.h.
iCPUCycle
unsigned long Scheduler::iCPUCycle
Definition at line 3085 of file TaskSchedulerDeclarations.h.
Referenced by getCpuLoadCycle().
iCPUIdle
unsigned long Scheduler::iCPUIdle
Definition at line 3086 of file TaskSchedulerDeclarations.h.
Referenced by getCpuLoadIdle().
iCPUStart
unsigned long Scheduler::iCPUStart
Definition at line 3084 of file TaskSchedulerDeclarations.h.
iCurrent
Task * Scheduler::iCurrent
Definition at line 3068 of file TaskSchedulerDeclarations.h.
Referenced by Task::disable(), and Task::enable().
iEnabled
volatile bool Scheduler::iEnabled
Definition at line 3070 of file TaskSchedulerDeclarations.h.
Referenced by disable(), and enable().
iFirst
Task* Scheduler::iFirst
Definition at line 3068 of file TaskSchedulerDeclarations.h.
Referenced by getFirstTask().
iHighPriority
Scheduler* Scheduler::iHighPriority
Definition at line 3080 of file TaskSchedulerDeclarations.h.
iInvokedTasks
unsigned long Scheduler::iInvokedTasks
Definition at line 3073 of file TaskSchedulerDeclarations.h.
Referenced by getInvokedTasks().
iLast
Task * Scheduler::iLast
Definition at line 3068 of file TaskSchedulerDeclarations.h.
Referenced by getLastTask().
iPaused
volatile bool Scheduler::iPaused
Definition at line 3070 of file TaskSchedulerDeclarations.h.
Referenced by pause(), and resume().
iTotalTasks
unsigned long Scheduler::iTotalTasks
Definition at line 3072 of file TaskSchedulerDeclarations.h.
Referenced by getTotalTasks().
The documentation for this class was generated from the following files:
src/TaskSchedulerDeclarations.h
src/TaskScheduler.h