TaskScheduler: StatusRequest Class Reference
StatusRequest Class Reference
Status Request object for event-driven task invocation.
#include <TaskSchedulerDeclarations.h>
Public Member Functions
StatusRequest ()
Default constructor.
void setWaiting (unsigned int aCount=1)
Activates Status Request object.
bool signal (int aStatus=0)
Signals completion of one event.
void signalComplete (int aStatus=0)
Signals completion of ALL events.
bool pending ()
Check if status request is pending (deprecated)
bool isPending ()
Check if status request is pending.
bool completed ()
Check if status request is completed (deprecated)
bool isCompleted ()
Check if status request is completed.
int getStatus ()
Get the status code.
int getCount ()
Get count of remaining events.
void setTimeout (unsigned long aTimeout)
Set timeout for this StatusRequest object.
unsigned long getTimeout ()
Get timeout interval.
void resetTimeout ()
Reset timeout counter.
long untilTimeout ()
Get time until timeout.
Public Attributes
unsigned int iCount
int iStatus
unsigned long iTimeout
unsigned long iStarttime
Friends
class Scheduler
Detailed Description
Status Request object for event-driven task invocation.
StatusRequest objects allow tasks to wait on an event and signal event completion to each other. This enables event-driven programming where one task can "signal" completion of its function via a StatusRequest object, and other tasks can "wait" on the same StatusRequest object.
Key features:
Can wait for multiple events (set via setWaiting())
Supports timeout functionality
Provides completion status codes
Thread-safe signaling mechanisms
Note
Each task has an internal StatusRequest object that is:
Always waits on 1 event (completion of this task)
Activated (set to "waiting" status) after Task is enabled
Completed after Task is disabled
See also
Task::waitFor(), Task::waitForDelayed()
Definition at line 723 of file TaskSchedulerDeclarations.h.
Constructor & Destructor Documentation
StatusRequest()
StatusRequest::StatusRequest () inline
Default constructor.
Creates Status Request object with "completed" status on creation.
Definition at line 473 of file TaskScheduler.h.
References Task::iStarttime, Task::iStatus, and Task::iTimeout.
Member Function Documentation
completed()
bool StatusRequest::completed () inline
Check if status request is completed (deprecated)
Returns
true if status request event has completed
Deprecated:
Use isCompleted() instead
Definition at line 779 of file TaskSchedulerDeclarations.h.
References isCompleted().
getCount()
int StatusRequest::getCount () inline
Get count of remaining events.
Returns
The count of events not yet completed
Typically by default a StatusRequest object only waits on 1 event. However, when waiting on multiple events, returns number of events not yet completed.
Definition at line 494 of file TaskScheduler.h.
getStatus()
int StatusRequest::getStatus () inline
Get the status code.
Returns
The status code passed to signal() and signalComplete() methods
Any positive number is considered successful completion status. A 0 (zero) is considered default successful completion status. Any negative number is considered an error code and unsuccessful completion.
Definition at line 493 of file TaskScheduler.h.
References Task::iStatus.
getTimeout()
unsigned long StatusRequest::getTimeout () inline
Get timeout interval.
Returns
The timeout interval for the current StatusRequest object
This is the full original interval, not the remaining time.
Definition at line 818 of file TaskSchedulerDeclarations.h.
References iTimeout.
isCompleted()
bool StatusRequest::isCompleted () inline
Check if status request is completed.
Returns
true if status request event has completed
Definition at line 492 of file TaskScheduler.h.
Referenced by completed().
isPending()
bool StatusRequest::isPending () inline
Check if status request is pending.
Returns
true if status request is still waiting for events to happen
Definition at line 491 of file TaskScheduler.h.
Referenced by pending().
pending()
bool StatusRequest::pending () inline
Check if status request is pending (deprecated)
Returns
true if status request is still waiting for events
Deprecated:
Use isPending() instead
Definition at line 766 of file TaskSchedulerDeclarations.h.
References isPending().
Referenced by Scheduler::timeUntilNextIteration().
resetTimeout()
void StatusRequest::resetTimeout () inline
Reset timeout counter.
Resets the current timeout counter to the original value. The timeout countdown starts from the beginning again.
Definition at line 545 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, and Task::iStarttime.
Referenced by Scheduler::processRequests().
setTimeout()
void StatusRequest::setTimeout (unsigned long aTimeout) inline
Set timeout for this StatusRequest object.
Parameters
aTimeout Timeout interval in milliseconds (or microseconds)
When enabled, the activated StatusRequest object will complete with the code TASK_SR_TIMEOUT if no other process calls its signal() or signalComplete() method.
Definition at line 811 of file TaskSchedulerDeclarations.h.
References iTimeout.
Referenced by Scheduler::processRequests().
setWaiting()
void StatusRequest::setWaiting (unsigned int aCount = 1) inline
Activates Status Request object.
Parameters
aCount Number of events to wait for (default = 1)
By default each object waits on one event only. If aCount is supplied, StatusRequest can wait on multiple events. For example, setWaiting(3) will wait on three signals - useful for waiting for completion of measurements from 3 sensors.
Definition at line 483 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, Task::iStarttime, and Task::iStatus.
Referenced by Task::enable(), and Scheduler::processRequests().
signal()
bool StatusRequest::signal (int aStatus = 0) inline
Signals completion of one event.
Parameters
aStatus Completion code (default = 0)
Returns
true if signal was processed successfully
Signals completion of the event to the StatusRequest object and passes a completion code. Passing a negative status code is considered reporting an error condition and will complete the status request regardless of how many outstanding signals it is still waiting for. Only the latest status code is kept.
Signals completion of the StatusRequest by one of the participating events
Parameters
aStatus - if provided, sets the return code of the StatusRequest: negative = error, 0 (default) = OK, positive = OK with a specific status code Negative status will complete Status Request fully (since an error occured).
Returns
: true, if StatusRequest is complete, false otherwise (still waiting for other events)
Definition at line 503 of file TaskScheduler.h.
References Task::iStatus.
Referenced by Scheduler::processRequests().
signalComplete()
void StatusRequest::signalComplete (int aStatus = 0) inline
Signals completion of ALL events.
Parameters
aStatus Completion code (default = 0)
Signals completion of ALL events to the StatusRequest object and passes a completion code. The status request completes regardless of how many events it is still waiting on.
Definition at line 511 of file TaskScheduler.h.
References Task::iStatus.
Referenced by Task::abort(), Task::cancel(), Task::disable(), Task::enable(), Scheduler::execute(), Scheduler::processRequests(), and Task::reset().
untilTimeout()
long StatusRequest::untilTimeout () inline
Get time until timeout.
Returns
Number of milliseconds (or microseconds) until timeout
The value could be negative if the timeout has already occurred.
Definition at line 549 of file TaskScheduler.h.
References __TASK_TIME_FUNCTION, Task::iStarttime, and Task::iTimeout.
Friends And Related Symbol Documentation
Scheduler
friend class Scheduler friend
Definition at line 724 of file TaskSchedulerDeclarations.h.
Member Data Documentation
iCount
unsigned int StatusRequest::iCount
Definition at line 836 of file TaskSchedulerDeclarations.h.
iStarttime
unsigned long StatusRequest::iStarttime
Definition at line 841 of file TaskSchedulerDeclarations.h.
Referenced by Scheduler::execute().
iStatus
int StatusRequest::iStatus
Definition at line 837 of file TaskSchedulerDeclarations.h.
iTimeout
unsigned long StatusRequest::iTimeout
Definition at line 840 of file TaskSchedulerDeclarations.h.
Referenced by Scheduler::execute(), getTimeout(), and setTimeout().
The documentation for this class was generated from the following files:
src/TaskSchedulerDeclarations.h
src/TaskScheduler.h