TaskScheduler: src/TaskScheduler.h File Reference
TaskScheduler.h File Reference
#include "TaskSchedulerDeclarations.h"
#include "TaskSchedulerSleepMethods.h"
Macros
#define _TASKSCHEDULER_H_
#define __TASK_TIME_FUNCTION() _task_millis()
Functions
__attribute__ ((weak)) bool _task_enqueue_request(_task_request_t *req)
static unsigned long _task_millis ()
static unsigned int _task_micros ()
static void _task_yield ()
Variables
Scheduler * iSleepScheduler
Global pointer to scheduler that controls sleep functionality.
SleepCallback iSleepMethod
Global pointer to custom sleep method.
static unsigned int __task_id_counter = 0
Scheduler * iCurrentScheduler
Macro Definition Documentation
__TASK_TIME_FUNCTION
#define __TASK_TIME_FUNCTION () _task_millis()
Definition at line 332 of file TaskScheduler.h.
_TASKSCHEDULER_H_
#define _TASKSCHEDULER_H_
Definition at line 298 of file TaskScheduler.h.
Function Documentation
__attribute__()
__attribute__ ((weak))
Definition at line 364 of file TaskScheduler.h.
_task_micros()
static unsigned int _task_micros () static
Definition at line 378 of file TaskScheduler.h.
Referenced by Scheduler::cpuLoadReset(), Scheduler::execute(), and Scheduler::getCpuLoadTotal().
_task_millis()
static unsigned long _task_millis () static
Definition at line 376 of file TaskScheduler.h.
_task_yield()
static void _task_yield () static
Definition at line 383 of file TaskScheduler.h.
Referenced by Scheduler::execute().
Variable Documentation
__task_id_counter
unsigned int __task_id_counter = 0 static
Definition at line 355 of file TaskScheduler.h.
Referenced by Task::Task(), and Task::Task().
iCurrentScheduler
Scheduler* iCurrentScheduler
Definition at line 359 of file TaskScheduler.h.
Referenced by Scheduler::currentScheduler(), and Scheduler::execute().
iSleepMethod
SleepCallback iSleepMethod
Global pointer to custom sleep method.
Definition at line 341 of file TaskScheduler.h.
Referenced by Scheduler::execute(), and Scheduler::setSleepMethod().
iSleepScheduler
Scheduler* iSleepScheduler
Global pointer to scheduler that controls sleep functionality.
Definition at line 340 of file TaskScheduler.h.
Referenced by Scheduler::execute(), and Scheduler::setSleepMethod().